<?php
define('ROOT_DIR', __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR);
define('CONFIG_DIR', ROOT_DIR.DIRECTORY_SEPARATOR.'config'.DIRECTORY_SEPARATOR);
define('DATA_DIR', ROOT_DIR.DIRECTORY_SEPARATOR.'data'.DIRECTORY_SEPARATOR);
define('ENGINE_DIR', ROOT_DIR.DIRECTORY_SEPARATOR.'engine'.DIRECTORY_SEPARATOR);
define('PABLIC_DIR', ROOT_DIR.DIRECTORY_SEPARATOR.'pablic'.DIRECTORY_SEPARATOR);
define('TEMPLATES_DIR', ROOT_DIR.DIRECTORY_SEPARATOR.'templates'.DIRECTORY_SEPARATOR);
define('IMG_DIR', ROOT_DIR.DIRECTORY_SEPARATOR.PABLIC_DIR.DIRECTORY_SEPARATOR.'img');

?>